### ISSUE TITLE
when i run npm run dev it will give me error like this 

### ISSUE THREAD

**Issue by ShubhamConversios** [joellord/remix-mongodb#2]
![image](https://github.com/mongodb-developer/remix/assets/154234771/1c95d38d-4d67-4615-903e-f7abe80551b8)

what can i do to solve this?

**Comment by joellord** [comment]
Thank you for reporting this. It seems like running the template on Node.js version 20 was causing the issue, as document [here](https://github.com/remix-run/remix/issues/6118).

The template is now using version 1.19.3, which fixes this issue.
